application: beer-explorer
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: beerexplorer.application
- url: /script
  static_dir: script
- url: /css
  static_dir: css
- url: /templates
  static_dir: templates
- url: /images
  static_dir: images

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest